2020-04-12 08:13:28,529 [INFO ]  Starting Rasa server on http://localhost:5005
2020-04-12 08:13:33,375 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/linux/.local/lib/python3.6/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/home/linux/.local/lib/python3.6/site-packages/sanic/server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "/home/linux/.local/lib/python3.6/site-packages/sanic/server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/core/run.py", line 239, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(endpoints.nlu or nlu_model)
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 54, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 274, in __init__
    self._load_interpreter()
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 297, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/nlu/components.py", line 718, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 231, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 857, in load
    index_tag_id_mapping, label_data, meta, data_example, model_dir
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 933, in _load_model
    model.build_for_predict(predict_data_example)
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/utils/tensorflow/models.py", line 201, in build_for_predict
    predict_data.as_tf_dataset, self.batch_predict, eager, "prediction"
  File "/home/linux/.local/lib/python3.6/site-packages/rasa/utils/tensorflow/models.py", line 298, in _get_tf_call_model_function
    tf_call_model_function(next(iter(init_dataset)))
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 964, in wrapper
    user_requested=True,
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 565, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/tmpmhrg0n3w.py", line 48, in tf__batch_predict
    ag__.if_stmt(cond_1, if_true_1, if_false_1, get_state_1, set_state_1, (), ('self.all_labels_embed', "out['i_scores']"))
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/operators/control_flow.py", line 920, in if_stmt
    return _py_if_stmt(cond, body, orelse)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/operators/control_flow.py", line 1029, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/tmpmhrg0n3w.py", line 38, in if_true_1
    cls = ag__.converted_call(self._last_token, (text_transformed, sequence_lengths), None, fscope)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 526, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 326, in convert
    free_nonglobal_var_names)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 240, in _convert_with_cache
    entity, program_ctx)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 473, in convert_entity_to_ast
    nodes, name, entity_info = convert_func_to_ast(o, program_ctx)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 673, in convert_func_to_ast
    node = node_to_graph(node, context)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 720, in node_to_graph
    node = converter.apply_(node, context, logical_expressions)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 408, in apply_
    node = standard_analysis(node, context)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/core/converter.py", line 386, in standard_analysis
    node = liveness.resolve(node, context, graphs)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/static_analysis/liveness.py", line 246, in resolve
    node = cross_function_analyzer.visit(node)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/static_analysis/liveness.py", line 123, in visit_FunctionDef
    node = self.generic_visit(node)
  File "/usr/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 317, in generic_visit
    new_node = self.visit(old_value)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 317, in generic_visit
    new_node = self.visit(old_value)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 317, in generic_visit
    new_node = self.visit(old_value)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 317, in generic_visit
    new_node = self.visit(old_value)
  File "/home/linux/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/pyct/transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "/usr/lib/python3.6/ast.py", line 252, in visit
    visitor = getattr(self, method, self.generic_visit)
  File "/home/linux/.local/lib/python3.6/site-packages/socketio/client.py", line 25, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
